name: Java CI

on:
  push:
    branches:
      - main
      - develop
      - dev-*  # Esto ejecutará el CI en cualquier rama que empiece con "dev/"
  pull_request:
    branches:
      - main
      - develop
      - dev/* 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # Puedes usar 'zulu', 'adopt', etc.
        java-version: '17'
        cache: 'maven' # Cachea dependencias de Maven para acelerar builds

    - name: Compilar con Maven
      run: mvn clean install
